# Generated by Django 4.0.1 on 2022-02-22 17:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roast', '0002_alter_roast_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roastDate', models.DateTimeField()),
                ('brewDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('brew_method', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Hario V60'), ('2', 'ChemX'), ('3', 'Origami'), ('4', 'Melitta'), ('5', 'Kalita'), ('6', 'Bee House'), ('7', 'Walkure')], max_length=32), blank=True, default=list, size=None)),
                ('roastID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brews', to='roast.roast')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brewDate'],
            },
        ),
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=2)),
                ('output', models.DecimalField(decimal_places=1, max_digits=3)),
                ('grind', models.DecimalField(decimal_places=1, max_digits=2)),
                ('TSD_score', models.IntegerField()),
                ('flavor_score', models.IntegerField()),
                ('comment', models.TextField(default=None, max_length=555)),
                ('is_best', models.BooleanField(default=False)),
                ('brewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.brew')),
            ],
        ),
    ]
