# Generated by Django 4.0.1 on 2022-02-22 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='brew_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Hario V60'), ('2', 'ChemX'), ('3', 'Origami'), ('4', 'Melitta'), ('5', 'Kalita'), ('6', 'Bee House'), ('7', 'Walkure')], max_length=32), default=list, size=None),
        ),
    ]
