# Generated by Django 4.0.1 on 2022-02-25 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_alter_brew_brew_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='brewDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brew',
            name='roastDate',
            field=models.DateField(),
        ),
    ]
