# Generated by Django 4.0.1 on 2022-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0006_alter_brew_brew_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
