# Generated by Django 4.0.1 on 2022-03-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0010_remove_brew_bestrecipieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='bestRecipieID',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='brew', to='brew.recipie'),
        ),
    ]
