# Generated by Django 4.0.1 on 2022-03-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0014_brew_bestrecipieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='bestRecipieID',
        ),
    ]
