# Generated by Django 4.0.1 on 2022-03-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0017_recipie_is_best'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='is_best',
        ),
    ]
