# Generated by Django 4.0.1 on 2022-03-10 01:55

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0019_brew_bestrecipieid_alter_brew_roastid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='bestRecipieID',
            field=models.ForeignKey(limit_choices_to={'brewID': builtins.id}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipie', to='brew.recipie'),
        ),
    ]
