# Generated by Django 4.0.1 on 2022-03-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0021_alter_brew_bestrecipieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='bestRecipieID',
            field=models.ForeignKey(limit_choices_to=models.Q(('recipie__brewID', 1)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipie', to='brew.recipie'),
        ),
    ]
