# Generated by Django 4.0 on 2022-06-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0023_alter_brew_bestrecipieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='bestRecipieID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipie', to='brew.recipie'),
        ),
    ]
