# Generated by Django 4.0.1 on 2022-02-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('variatal', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('notes', models.TextField(default=None, max_length=555)),
                ('thumb', models.ImageField(blank=True, default='main/images/pixelated-coffee-bag.png', upload_to='')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
