# Generated by Django 4.0.1 on 2022-02-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roast',
            options={'ordering': ['name']},
        ),
    ]
